//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `btn_receive`.
    static let btn_receive = Rswift.ImageResource(bundle: R.hostingBundle, name: "btn_receive")
    /// Image `btn_sell`.
    static let btn_sell = Rswift.ImageResource(bundle: R.hostingBundle, name: "btn_sell")
    /// Image `icon_drop_down`.
    static let icon_drop_down = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_drop_down")
    
    /// `UIImage(named: "btn_receive", bundle: ..., traitCollection: ...)`
    static func btn_receive(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.btn_receive, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "btn_sell", bundle: ..., traitCollection: ...)`
    static func btn_sell(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.btn_sell, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon_drop_down", bundle: ..., traitCollection: ...)`
    static func icon_drop_down(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_drop_down, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `ConverterReceiveTableViewCell`.
    static let converterReceiveTableViewCell = _R.nib._ConverterReceiveTableViewCell()
    /// Nib `ConverterSellTableViewCell`.
    static let converterSellTableViewCell = _R.nib._ConverterSellTableViewCell()
    
    /// `UINib(name: "ConverterReceiveTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.converterReceiveTableViewCell) instead")
    static func converterReceiveTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.converterReceiveTableViewCell)
    }
    
    /// `UINib(name: "ConverterSellTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.converterSellTableViewCell) instead")
    static func converterSellTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.converterSellTableViewCell)
    }
    
    static func converterReceiveTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ConverterReceiveTableViewCell? {
      return R.nib.converterReceiveTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ConverterReceiveTableViewCell
    }
    
    static func converterSellTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ConverterSellTableViewCell? {
      return R.nib.converterSellTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ConverterSellTableViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `converterReceiveTableViewCell`.
    static let converterReceiveTableViewCell: Rswift.ReuseIdentifier<ConverterReceiveTableViewCell> = Rswift.ReuseIdentifier(identifier: "converterReceiveTableViewCell")
    /// Reuse identifier `converterSellTableViewCell`.
    static let converterSellTableViewCell: Rswift.ReuseIdentifier<ConverterSellTableViewCell> = Rswift.ReuseIdentifier(identifier: "converterSellTableViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _ConverterReceiveTableViewCell.validate()
      try _ConverterSellTableViewCell.validate()
    }
    
    struct _ConverterReceiveTableViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = ConverterReceiveTableViewCell
      
      let bundle = R.hostingBundle
      let identifier = "converterReceiveTableViewCell"
      let name = "ConverterReceiveTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ConverterReceiveTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ConverterReceiveTableViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "btn_receive", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'btn_receive' is used in nib 'ConverterReceiveTableViewCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon_drop_down", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon_drop_down' is used in nib 'ConverterReceiveTableViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct _ConverterSellTableViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = ConverterSellTableViewCell
      
      let bundle = R.hostingBundle
      let identifier = "converterSellTableViewCell"
      let name = "ConverterSellTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ConverterSellTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ConverterSellTableViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "btn_sell", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'btn_sell' is used in nib 'ConverterSellTableViewCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon_drop_down", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon_drop_down' is used in nib 'ConverterSellTableViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
